# Generated by Django 5.0 on 2024-02-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histoire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Histoire',
        ),
    ]
